image:
  file: .gitpod.Dockerfile
tasks:
  - name: install package and check zsh and zsh plugin
    init: |-
      sudo chmod +x ./.gitpod/oh-my-zsh.sh && ./.gitpod/oh-my-zsh.sh
  - name: change default shell to zsh and start zsh shell
    command: sudo chsh -s $(which zsh) && zsh
  - name: install flake8 for python lint
    command: python -m pip install -U flake8
  - name: install yapf for python formatting
    command: python -m pip install -U yapf
github:
  prebuilds:
    addCheck: true
    addBadge: true
    addLabel: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker-spanish
    - ms-python.python
